name: Android Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Retrieve the secret and decode it to a file
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}

        run: |
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -di > app/google-services.json
          
      - name: Run Lint check
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: ./gradlew ktlintCheck

      - name: Run Tests with Gradle
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: ./gradlew test

      - name: Build with Gradle
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
          APKSIGN_KEYSTORE_BASE64: ${{ secrets.APKSIGN_KEYSTORE_BASE64 }}
          APKSIGN_KEYSTORE_PASS: ${{ secrets.APKSIGN_KEYSTORE_PASS }}
          APKSIGN_KEY_ALIAS: ${{ secrets.APKSIGN_KEY_ALIAS }}
          APKSIGN_KEY_PASS: ${{ secrets.APKSIGN_KEY_PASS }}
        run: |
          echo $APKSIGN_KEYSTORE_BASE64 | base64 -di > release.keystore
          export APKSIGN_KEYSTORE=`pwd`/release.keystore
          ./gradlew assembleRelease
          mv app/build/outputs/apk/release/*.apk .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: YourSpace APK
          path: YourSpace*.apk
          retention-days: 2
